import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.setDefaultTimeout(6000);
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await mkdir('artifacts', { recursive: true });
const money = () => page.evaluate(() => civic.city.money);
const point = (x, y) => page.evaluate(({x,y}) => civic.renderer.project(x+.5,y+.5), {x,y});
const tile = (x,y) => page.evaluate(({x,y}) => civic.city.tiles[y*40+x], {x,y});
try {
  await page.goto(process.env.CIVIC_TEST_URL || 'http://127.0.0.1:4173');
  await page.waitForFunction(() => window.civic?.city?.tiles.length === 1600);
  const initial = await money();
  await page.waitForTimeout(2700);
  assert.equal(await page.evaluate(() => civic.city.month), 0, 'Starts paused');
  await page.getByRole('button', {name:'Transport',exact:true}).click();
  await page.locator('[data-tool="road"]').click();
  const target = await page.evaluate(() => civic.city.tiles.find(t => {
    const p=civic.renderer.project(t.x+.5,t.y+.5);
    return t.type==='empty' && t.terrain==='grass' && p.x>300 && p.x<950 && p.y>220 && p.y<700 && document.elementFromPoint(p.x,p.y)?.id==='city-canvas';
  }));
  assert.ok(target);
  const p=await point(target.x,target.y);
  await page.mouse.move(p.x,p.y);await page.mouse.down();
  assert.equal(await money(),initial,'Pointer down only previews');
  await page.keyboard.press('Escape');await page.mouse.up();
  assert.equal((await tile(target.x,target.y)).type,'empty','Escape cancels stroke');
  await page.mouse.click(p.x,p.y);
  assert.equal((await tile(target.x,target.y)).type,'road','Release builds');
  assert.equal(await money(),initial-50);
  await page.keyboard.press('ControlOrMeta+z');
  assert.equal((await tile(target.x,target.y)).type,'empty','Undo restores tile');
  assert.equal(await money(),initial,'Undo restores money');
  await page.mouse.click(p.x,p.y);
  await page.getByRole('button',{name:'Save city',exact:true}).click();
  await page.locator('[data-tool="bulldoze"]').click();await page.mouse.click(p.x,p.y);
  assert.equal((await tile(target.x,target.y)).type,'empty');
  await page.getByRole('button',{name:'Load city',exact:true}).click();
  assert.equal((await tile(target.x,target.y)).type,'road');
  await page.getByRole('button',{name:'Open budget',exact:true}).click();
  const tax=page.getByRole('slider',{name:'Residential tax rate',exact:true});
  await tax.fill('12');await tax.dispatchEvent('input');
  assert.deepEqual(await page.evaluate(()=>civic.getStats().taxes),{residential:12,commercial:9,industrial:9},'Taxes remain independent');
  await page.getByRole('button',{name:'Take a $10,000 loan',exact:true}).click();
  assert.equal(await page.evaluate(()=>civic.city.debt),10000);
  await page.getByRole('button',{name:'Open budget',exact:true}).click();
  await page.getByRole('button',{name:'Repay outstanding loan',exact:true}).click();
  assert.equal(await page.evaluate(()=>civic.city.debt),0,'Repay clears affordable debt');
  await page.getByRole('button',{name:'City report',exact:true}).click();
  assert.ok(await page.getByRole('dialog',{name:'City Report',exact:true}).isVisible());await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Advisors',exact:true}).click();
  assert.ok(await page.getByRole('dialog',{name:'Advisors',exact:true}).isVisible());await page.keyboard.press('Escape');
  await page.locator('[data-overlay="crime"]').click();
  assert.equal(await page.evaluate(()=>civic.renderer.overlay),'crime');
  await page.locator('[data-overlay="none"]').click();
  for(let i=1;i<=4;i++) {await page.getByRole('button',{name:'Rotate right',exact:true}).click();assert.equal(await page.evaluate(()=>civic.renderer.rotation),i%4);}
  await page.keyboard.press('3');await page.waitForFunction(()=>civic.city.month>0);await page.keyboard.press('0');
  await page.keyboard.press('Escape');await page.waitForTimeout(100);
  await page.screenshot({path:'artifacts/civic3000-desktop.png'});
  await page.getByRole('button',{name:'Toggle day/night',exact:true}).click();await page.waitForTimeout(100);
  assert.equal(await page.evaluate(()=>civic.renderer.night),true);
  await page.screenshot({path:'artifacts/civic3000-night.png'});
  await page.getByRole('button',{name:'Toggle day/night',exact:true}).click();
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(150);
  await page.getByTitle('Home view [H]',{exact:true}).click();await page.waitForTimeout(200);
  for(const name of ['Open budget','Save city','Load city','New city','Toggle tools']) {
    const box=await page.getByRole('button',{name,exact:true}).boundingBox();
    assert.ok(box && box.x>=0 && box.x+box.width<=390,`${name} reachable on mobile`);
  }
  await page.getByRole('button',{name:'Toggle tools',exact:true}).click();
  assert.ok(await page.locator('#right-dock').isVisible());
  await page.getByRole('button',{name:'Toggle tools',exact:true}).click();
  await page.screenshot({path:'artifacts/civic3000-mobile.png'});
  await page.getByRole('button',{name:'New city',exact:true}).click();
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  assert.ok(await page.evaluate(()=>civic.city.population>0));
  await page.getByRole('button',{name:'New city',exact:true}).click();
  await page.getByRole('button',{name:'Sandbox ($50K)',exact:true}).click();
  assert.equal(await page.evaluate(()=>civic.city.population),0);
  assert.equal(await money(),50000);
  await page.getByRole('button',{name:'Load city',exact:true}).click();
  assert.ok(await page.evaluate(()=>civic.city.population>0));
  assert.deepEqual(errors,[],'No runtime errors');
  console.log('Browser passed: preview/cancel/commit/undo, saving, independent taxes, loans, reports, advisors, overlays, rotation, simulation, desktop/night/mobile and new-city confirmation.');
} finally { await browser.close(); }
