"""Export tightly cropped WebP frames and exact screen-space anchor metadata."""
from pathlib import Path
from PIL import Image
import json, hashlib, argparse
p=argparse.ArgumentParser();p.add_argument('--input',default='artifacts/civic-renders');args=p.parse_args()
root=Path(__file__).resolve().parents[2];source=root/args.input;out=root/'public/assets/civic';out.mkdir(parents=True,exist_ok=True)
manifest={};total=0
for meta_path in sorted(source.glob('*.json')):
    meta=json.loads(meta_path.read_text());frames={}
    for key,frame in meta['frames'].items():
        image=Image.open(source/frame['file']).convert('RGBA')
        bounds=image.getchannel('A').getbbox()
        if bounds is None:raise ValueError(f'Empty frame: {frame}')
        if bounds[0]==0 or bounds[1]==0 or bounds[2]==image.width or bounds[3]==image.height:raise ValueError(f'Clipped frame: {frame}')
        # Retain two pixels around the antialiased silhouette.
        bounds=(max(0,bounds[0]-2),max(0,bounds[1]-2),min(image.width,bounds[2]+2),min(image.height,bounds[3]+2))
        image=image.crop(bounds)
        import io
        buffer=io.BytesIO();image.save(buffer,format='WEBP',quality=88,method=6,exact=True)
        content=buffer.getvalue();digest=hashlib.sha256(content).hexdigest()[:10]
        name=f"{meta['type']}-{key}.{digest}.webp";(out/name).write_bytes(content);total+=len(content)
        frames[key]={'file':name,'width':image.width,'height':image.height,'anchor':[round(frame['anchor'][0]-bounds[0],4),round(frame['anchor'][1]-bounds[1],4)]}
    manifest[meta['type']]={'tiles':meta['tiles'],'scale':meta['scale'],'height':round(meta['maxHeight']+1),'frames':frames}
(root/'src/civic-sprite-manifest.js').write_text('// Generated by tools/civic_art/package.py. Coordinates are baked pixel anchors.\nexport const CIVIC_SPRITES = '+json.dumps(manifest,indent=2)+';\n')
# Prune obsolete outputs only after every replacement frame packaged correctly.
keep={frame['file'] for spec in manifest.values() for frame in spec['frames'].values()}
for old in out.glob('*.webp'):
    if old.name not in keep:old.unlink()
print(f'{len(manifest)} buildings, {len(keep)} frames, {total/1024/1024:.2f} MiB compressed')
