"""Export alpha-cropped WebP sprites, stable anchors and measured heights."""
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor
from PIL import Image
import json, hashlib, argparse, io

REGISTRY = json.loads((Path(__file__).parent/'registry.json').read_text())
TYPES = set(REGISTRY)
STATES = {f'{state}-{r}' for state in ['day','night','unpowered'] for r in range(4)}


def encode(job):
    source, out, kind, key, frame = job
    image = Image.open(Path(source)/frame['file']).convert('RGBA')
    bounds = image.getchannel('A').getbbox()
    if bounds is None: raise ValueError(f'Empty frame: {kind} {key}')
    if bounds[0] == 0 or bounds[1] == 0 or bounds[2] == image.width or bounds[3] == image.height:
        raise ValueError(f'Clipped frame: {kind} {key}')
    bounds = (max(0,bounds[0]-2), max(0,bounds[1]-2), min(image.width,bounds[2]+2), min(image.height,bounds[3]+2))
    image = image.crop(bounds)
    buffer = io.BytesIO(); image.save(buffer, format='WEBP', quality=88, method=6, exact=True)
    content = buffer.getvalue(); digest = hashlib.sha256(content).hexdigest()[:10]
    name = f'{kind}-{key}.{digest}.webp'; (Path(out)/name).write_bytes(content)
    return kind, key, {'file':name, 'width':image.width, 'height':image.height,
        'anchor':[round(frame['anchor'][0]-bounds[0],4), round(frame['anchor'][1]-bounds[1],4)]}


def main():
    p = argparse.ArgumentParser(); p.add_argument('--input',default='artifacts/civic-renders')
    p.add_argument('--types', help='Incrementally replace comma-separated types in an existing complete export')
    args = p.parse_args()
    root = Path(__file__).resolve().parents[2]; source = root/args.input; out = root/'public/assets/civic'; out.mkdir(parents=True,exist_ok=True)
    if args.types and not (out/'catalog.json').is_file():
        raise ValueError('Incremental packaging requires the tracked catalog.json; restore it or bake and package all types first')
    manifest = json.loads((out/'catalog.json').read_text()) if args.types else {}
    selected = {name for name,spec in REGISTRY.items() if spec['family']==args.types} if args.types in {'civic','power'} else set(args.types.split(',')) if args.types else TYPES
    if not selected <= TYPES: raise ValueError('Unknown building type')
    jobs = []
    for kind in sorted(selected):
        meta = json.loads((source/f'{kind}.json').read_text())
        if set(meta['frames']) != STATES: raise ValueError(f'{kind}: render all 12 frames before packaging')
        manifest[kind] = {'tiles':meta['tiles'], 'scale':meta['scale'], 'height':round(meta['maxHeight']+1), 'frames':{}}
        jobs += [(str(source),str(out),kind,key,frame) for key,frame in meta['frames'].items()]
    with ProcessPoolExecutor(max_workers=4) as pool:
        for kind,key,frame in pool.map(encode,jobs): manifest[kind]['frames'][key] = frame
    for kind, spec in manifest.items():
        spec.update({key:value for key,value in REGISTRY[kind].items() if key in {'family','label','description'}})
    manifest = dict(sorted(manifest.items()))
    if set(manifest) != TYPES or any(set(s['frames']) != STATES for s in manifest.values()):
        raise ValueError('Incomplete building catalog; bake and package all registered types first')
    (root/'src/civic-sprite-manifest.js').write_text('// Generated by tools/civic_art/package.py. Coordinates are baked pixel anchors.\nexport const CIVIC_SPRITES = '+json.dumps(manifest,indent=2)+';\n')
    (out/'catalog.json').write_text(json.dumps(manifest,separators=(',',':')))
    keep = {frame['file'] for spec in manifest.values() for frame in spec['frames'].values()}
    # Prune only after every replacement has successfully encoded.
    for old in out.glob('*.webp'):
        if old.name not in keep: old.unlink()
    total = sum((out/name).stat().st_size for name in keep)
    print(f'{len(manifest)} buildings, {len(keep)} frames, {total/1024/1024:.2f} MiB compressed')

if __name__ == '__main__': main()
