"""Export alpha-cropped WebP sprites, stable anchors and measured heights."""
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor
from PIL import Image
import json, hashlib, argparse, io

REGISTRY = json.loads((Path(__file__).parent/'registry.json').read_text())
TYPES = set(REGISTRY)
STATES = {f'{state}-{r}' for state in ['day','night','unpowered'] for r in range(4)}


def expected_frames(kind):
    return {key+(f'-v{i}' if i else '') for i in range(len(REGISTRY[kind].get('variants',[None]))) for key in STATES}


def write_manifest(path, manifest):
    """Write the sprite manifest as a string handed to JSON.parse.

    Spelled as an object literal this is 1.2 MB of JavaScript the engine has to
    parse as code before the first frame can be drawn: every key a possible
    identifier, every value a possible expression. Inside JSON.parse it is one
    string literal to scan and then a purpose-built parser that knows the shape
    of what it is reading. Measured on this manifest, importing the module goes
    from about 10 ms to about 7 ms, and the source file drops from 1.27 MB to
    0.76 MB. The minified bundle grows by about 59 KB, because JSON quotes every
    key where a minifier could drop the quotes, which is roughly 2 KB once
    compressed. The module's export is identical either way.

    ensure_ascii is on, and the escaping depends on it. It leaves every
    non-ASCII character as a \\uXXXX sequence, so the payload cannot contain a
    raw newline, or U+2028 and U+2029, which end a line in JavaScript but are
    ordinary characters in JSON and are the pair a hand-rolled escape usually
    misses. That leaves exactly two characters that could end the string early
    or change what follows it, and the backslash is replaced first, or it would
    escape the escapes added after it.

    allow_nan is off. Python writes NaN and Infinity happily and JSON.parse
    rejects both, which would ship a module that throws the moment it is
    imported and a game that never starts. Better to fail here, where somebody
    is watching.
    """
    payload = (json.dumps(manifest, separators=(',', ':'), ensure_ascii=True, allow_nan=False)
               .replace('\\', '\\\\').replace("'", "\\'"))
    path.write_text(
        '// Generated by tools/civic_art/package.py. Coordinates are baked pixel anchors.\n'
        '// Handed to JSON.parse rather than written as an object literal: see write_manifest().\n'
        f"export const CIVIC_SPRITES = JSON.parse('{payload}');\n")


def encode(job):
    source, out, kind, key, frame = job
    image = Image.open(Path(source)/frame['file']).convert('RGBA')
    bounds = image.getchannel('A').getbbox()
    if bounds is None: raise ValueError(f'Empty frame: {kind} {key}')
    if bounds[0] == 0 or bounds[1] == 0 or bounds[2] == image.width or bounds[3] == image.height:
        raise ValueError(f'Clipped frame: {kind} {key}')
    bounds = (max(0,bounds[0]-2), max(0,bounds[1]-2), min(image.width,bounds[2]+2), min(image.height,bounds[3]+2))
    image = image.crop(bounds)
    buffer = io.BytesIO(); image.save(buffer, format='WEBP', quality=88, method=6, exact=True)
    content = buffer.getvalue(); digest = hashlib.sha256(content).hexdigest()[:10]
    name = f'{kind}-{key}.{digest}.webp'; (Path(out)/name).write_bytes(content)
    return kind, key, {'file':name, 'width':image.width, 'height':image.height,
        'anchor':[round(frame['anchor'][0]-bounds[0],4), round(frame['anchor'][1]-bounds[1],4)]}


def main():
    p = argparse.ArgumentParser(); p.add_argument('--input',default='artifacts/civic-renders')
    p.add_argument('--jobs',type=int,choices=range(1,33),default=4,help='Parallel image encoders (default: 4)')
    p.add_argument('--types', help='Incrementally replace comma-separated types in an existing complete export')
    args = p.parse_args()
    root = Path(__file__).resolve().parents[2]; source = root/args.input; out = root/'public/assets/civic'; out.mkdir(parents=True,exist_ok=True)
    # The catalogue sits beside the pages, not under assets/. Every file under
    # assets/ carries a content hash and is cached for a year by public/_headers;
    # the catalogue keeps one name and is rewritten whenever art is baked, so a
    # year-long cache would leave a returning visitor reading a list of sprites
    # that no longer exist.
    catalog = root/'public/civic-catalog.json'
    lighting=json.loads((root/'src/sunlight-config.json').read_text())['version']
    if args.types and not catalog.is_file():
        raise ValueError('Incremental packaging requires the tracked civic-catalog.json; restore it or bake and package all types first')
    manifest = json.loads(catalog.read_text()) if args.types else {}
    # A type removed from the registry leaves the catalog; its frames are pruned below.
    for stale in set(manifest) - TYPES: del manifest[stale]
    selected = {name for name,spec in REGISTRY.items() if spec['family']==args.types} if args.types in {spec['family'] for spec in REGISTRY.values()} else set(args.types.split(',')) if args.types else TYPES
    if not selected <= TYPES: raise ValueError('Unknown building type')
    if any(spec.get('lighting') != lighting for kind,spec in manifest.items() if kind not in selected):
        raise ValueError('Mixed lighting catalog; rebuild and package all types together')
    jobs = []
    for kind in sorted(selected):
        meta = json.loads((source/f'{kind}.json').read_text())
        if meta.get('lighting') != lighting: raise ValueError(f'{kind}: lighting differs; rebuild every view with {lighting}')
        if set(meta['frames']) != expected_frames(kind): raise ValueError(f'{kind}: render all rotations, lighting states and registered variants before packaging')
        footprint = meta.get('footprint') or dict(w=meta['tiles'], h=meta['tiles'])
        expected = REGISTRY[kind].get('footprint') or dict(w=REGISTRY[kind]['tiles'], h=REGISTRY[kind]['tiles'])
        if footprint != expected: raise ValueError(f'{kind}: render footprint differs from registry')
        manifest[kind] = {**({'footprint':footprint} if 'footprint' in REGISTRY[kind] else {'tiles':meta['tiles']}), 'scale':meta['scale'], 'height':round(meta['maxHeight']+1), **({'lighting':meta['lighting']} if 'lighting' in meta else {}), 'frames':{}}
        jobs += [(str(source),str(out),kind,key,frame) for key,frame in meta['frames'].items()]
    with ProcessPoolExecutor(max_workers=args.jobs) as pool:
        for kind,key,frame in pool.map(encode,jobs): manifest[kind]['frames'][key] = frame
    for kind, spec in manifest.items():
        spec.update({key:value for key,value in REGISTRY[kind].items() if key in {'family','label','description','variants','zone'}})
    manifest = dict(sorted(manifest.items()))
    if set(manifest) != TYPES or any(set(s['frames']) != expected_frames(kind) for kind,s in manifest.items()):
        raise ValueError('Incomplete building catalog; bake and package all registered types first')
    write_manifest(root/'src/civic-sprite-manifest.js', manifest)
    catalog.write_text(json.dumps(manifest,separators=(',',':')))
    keep = {frame['file'] for spec in manifest.values() for frame in spec['frames'].values()}
    # Prune only after every replacement has successfully encoded.
    for old in out.glob('*.webp'):
        if old.name not in keep: old.unlink()
    total = sum((out/name).stat().st_size for name in keep)
    print(f'{len(manifest)} buildings, {len(keep)} frames, {total/1024/1024:.2f} MiB compressed')

if __name__ == '__main__': main()
